### ISSUE TITLE
can node attribute names overlap with edge attribute names? 

### ISSUE THREAD

**Issue by judgelord** [judgelord/netlit#4]
@ngreifer, the draft docs `review.Rd` say that "Node attribute names may not be the same as any edge attribute names." Is this true? Must it be true? Since `review()` returns separate `edgelist` and `nodelist` objects, I'm not sure why they can't have the same names (it may not be a good idea, but as a matter of code, I don't see the conflict).

**Comment by ngreifer** [comment]
You're right, I don't think this is an issue. It would be an issue if the `nodelist` and `edgelist` were merged by a downstream function. I believe you had that in a prior version of the documentation and I just preserved it without questioning.

**Comment by judgelord** [comment]
ok; great; thanks! Just wanted to confirm.
